language: scala
scala:
  - 2.11.8

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: yaooqinn@hotmail.com
  name: Kent Yao
  on:
    branch: master

install:
  - mvn install -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn package -q -Dmaven.javadoc.skip=true -B -V
  - mvn package -Pspark-2.2 -P all -q -Dmaven.javadoc.skip=true -B -V
  - mvn package -Pspark-2.3 -P all -q -Dmaven.javadoc.skip=true -B -V
